# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-ast
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^.+\.min\.(js|css)$
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.270
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        stages: [commit]
        exclude: >
          (?x)^(
              (.*)/static|
              (.*)/vendors|
              ^.+\.html$|
              package-lock.json|
              ^.+\.min\.(js|css)$
          )$
        additional_dependencies:
          - prettier@2.8.8
