version: "3.8"

services:
  app:
    build:
      context: .
      args:
        DEVELOPMENT: 1
    command: tail -f /dev/null
    volumes:
      - ./:/home/zednews/app/
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=zednews_dev_user
      - POSTGRES_PASSWORD=zednews_dev_password
      - POSTGRES_DB=zednews_dev_db
      - PGUSER=zednews_dev_user
      - PGPASSWORD=zednews_dev_password
      - PGDATABASE=zednews_dev_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
