services:
  app:
    build:
      context: .
      args:
        DEVELOPMENT: ${DEVELOPMENT:-0}
    command: tail -f /dev/null
    volumes:
      - ./:/home/zednews/app/
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.8
    expose:
      - 5432
    environment:
      - POSTGRES_USER=zednews_dev_user
      - POSTGRES_PASSWORD=zednews_dev_password
      - POSTGRES_DB=zednews_dev_db
      - PGUSER=zednews_dev_user
      - PGPASSWORD=zednews_dev_password
      - PGDATABASE=zednews_dev_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgweb:
    image: sosedoff/pgweb:0.16.2
    ports:
      - 8081:8081
    environment:
      - PGWEB_DATABASE_URL=postgres://zednews_dev_user:zednews_dev_password@db:5432/zednews_dev_db?sslmode=disable
    depends_on:
      - db

volumes:
  postgres_data:
