[project]
name = "zed-news"
version = "0.2.0"
description = "news podcast on auto-pilot"
readme = "README.md"
requires-python = "~=3.10"
authors = [
  {name = "Victor Miti", email = "victormiti@gmail.com"}
]
dependencies = [
  "aerich",
  "apprise",
  "asyncpg",
  "Babel",
  "beautifulsoup4",
  "boto3",
  "bpython",
  "cohere",
  "colorama",
  "eyed3",
  "fake-useragent",
  "feedparser",
  "invoke",
  "jinja2",
  "langchain",
  "num2words",
  "openai",
  "tortoise-orm[psycopg]",
  "psycopg2-binary",
  "python-dateutil",
  "python-dotenv",
  "pytz",
  "requests",
  "tiktoken",
  "tomli",
]

[project.optional-dependencies]
dev = [
  "black",
  "commitizen",
  "coverage[toml]",
  "DSLR",
  "pip-tools",
  "pre-commit",
  "ruff",
]

[tool.setuptools]
py-modules = []

[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | node_modules
    | build
    | dist
  )/
)
'''

[tool.ruff]
line-length = 120
target-version = "py310"
select = ["B", "C", "E", "F", "W", "B9"]
ignore = ["E203", "E266", "E501", "F403", "F401"]
exclude = [
  ".git",
  "__pycache__",
  "node_modules",
  "public",
  "venv",
]

[tool.ruff.isort]
known-first-party = ["app"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[tool.ruff.pycodestyle]
max-doc-length = 120

[tool.ruff.mccabe]
max-complexity = 10

[tool.coverage.run]
include = ["app/core/*"]
branch = true   # Measure branch coverage

[tool.coverage.report]
skip_covered = true
show_missing = true

[tool.commitizen]
version_provider = "pep621"
version_files = [
    "app/__init__.py",
    "cron.sh",
]
tag_format = "v$major.$minor.$patch"
annotated_tag = true
update_changelog_on_bump = false

[tool.aerich]
tortoise_orm = "app.core.db.config.TORTOISE_ORM"
location = "./aerich/migrations"
src_folder = "./."
